# Generated by Django 4.0.4 on 2022-10-10 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('linkedin_names', models.CharField(blank=True, max_length=500, null=True, verbose_name='Linkedin Names')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('head_count', models.IntegerField(blank=True, null=True, verbose_name='Head Count')),
                ('founding_date', models.DateField(verbose_name='Founding Date')),
                ('most_recent_raise', models.IntegerField(blank=True, null=True, verbose_name='Recent Raise')),
                ('most_recent_valuation', models.IntegerField(blank=True, null=True, verbose_name='Recent Valuation')),
                ('investors', models.CharField(blank=True, max_length=500, null=True, verbose_name='Investors')),
                ('know_total_funding', models.IntegerField(blank=True, null=True, verbose_name='Recent Valuation')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'People',
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('group_start_date', models.DateField(verbose_name='Group Start Date')),
                ('group_end_date', models.DateField(verbose_name='Group End Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='domain.company', verbose_name='Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='domain.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work Histories',
                'db_table': 'work_history',
            },
        ),
    ]
