# Generated by Django 4.0.4 on 2022-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='head_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Head Count'),
        ),
        migrations.AlterField(
            model_name='company',
            name='know_total_funding',
            field=models.FloatField(blank=True, null=True, verbose_name='Recent Valuation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='most_recent_raise',
            field=models.FloatField(blank=True, null=True, verbose_name='Recent Raise'),
        ),
        migrations.AlterField(
            model_name='company',
            name='most_recent_valuation',
            field=models.FloatField(blank=True, null=True, verbose_name='Recent Valuation'),
        ),
    ]
