# Generated by Django 4.0.4 on 2022-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_company_head_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='investors',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Investors'),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_names',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Linkedin Names'),
        ),
    ]
