# Generated by Django 4.0.4 on 2022-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_alter_company_investors_alter_company_linkedin_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founding_date',
            field=models.DateField(null=True, verbose_name='Founding Date'),
        ),
    ]
