# Generated by Django 4.0.4 on 2022-10-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0011_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_history', to='domain.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_history', to='domain.person', verbose_name='Person'),
        ),
    ]
