# Generated by Django 4.0.4 on 2022-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0012_alter_workhistory_company_alter_workhistory_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='group_end_date',
            field=models.DateField(null=True, verbose_name='Group End Date'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='group_start_date',
            field=models.DateField(null=True, verbose_name='Group Start Date'),
        ),
    ]
