# Generated by Django 4.0.4 on 2022-10-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_alter_workhistory_group_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_history', to='domain.company', verbose_name='Company'),
        ),
    ]
