# Generated by Django 4.0.4 on 2022-10-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0014_alter_workhistory_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
